create table if not exists public.demandes_clients (
  id bigint generated by default as identity primary key,
  client text not null,
  commande_id bigint,
  demande text not null,
  date_demande date not null default current_date,
  date_echeance date,
  priorite text not null default 'Normale',
  statut text not null default 'À confirmer',
  notes text,
  created_by uuid not null references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists demandes_clients_echeance_idx on public.demandes_clients (date_echeance, statut);
alter table public.demandes_clients enable row level security;
create policy demandes_clients_select on public.demandes_clients for select to authenticated using (true);
create policy demandes_clients_insert on public.demandes_clients for insert to authenticated with check (created_by = (select auth.uid()));
create policy demandes_clients_update on public.demandes_clients for update to authenticated using (true) with check (true);
create policy demandes_clients_delete_admin on public.demandes_clients for delete to authenticated using ((select private.is_admin()));
create trigger protect_audit before update on public.demandes_clients for each row execute function private.protect_audit_fields();
grant select, insert, update, delete on public.demandes_clients to authenticated;
grant usage, select on sequence public.demandes_clients_id_seq to authenticated;
