alter table public.commandes
  add column if not exists booking_no text,
  add column if not exists compagnie_maritime text,
  add column if not exists agent_maritime text,
  add column if not exists booking_date date;

alter table public.factures add column if not exists agent_maritime text;

create table if not exists public.bookings_maritimes (
  id bigint generated by default as identity primary key,
  commande_id bigint not null unique references public.commandes(id) on delete cascade,
  compagnie text not null,
  numero_booking text not null,
  agent_maritime text,
  ocean_freight_usd numeric not null default 0,
  exchange_rate numeric not null default 0,
  ocean_freight_rmb numeric not null default 0,
  date_booking date not null default current_date,
  statut text not null default 'Confirmé',
  notes text,
  created_by uuid not null references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bookings_maritimes_created_by_idx on public.bookings_maritimes(created_by);
create index if not exists bookings_maritimes_updated_by_idx on public.bookings_maritimes(updated_by);
alter table public.bookings_maritimes enable row level security;
drop policy if exists bookings_maritimes_select on public.bookings_maritimes;
create policy bookings_maritimes_select on public.bookings_maritimes for select to authenticated using (true);
drop policy if exists bookings_maritimes_insert on public.bookings_maritimes;
create policy bookings_maritimes_insert on public.bookings_maritimes for insert to authenticated with check (created_by = (select auth.uid()));
drop policy if exists bookings_maritimes_update on public.bookings_maritimes;
create policy bookings_maritimes_update on public.bookings_maritimes for update to authenticated using (true) with check (true);
drop policy if exists bookings_maritimes_delete_admin on public.bookings_maritimes;
create policy bookings_maritimes_delete_admin on public.bookings_maritimes for delete to authenticated using ((select private.is_admin()));
grant select, insert, update, delete on table public.bookings_maritimes to authenticated;
grant usage, select on sequence public.bookings_maritimes_id_seq to authenticated;
