create schema if not exists private;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'employee' check (role in ('admin','employee')),
  created_at timestamptz not null default now()
);

create or replace function private.is_admin()
returns boolean language sql stable security definer set search_path = ''
as $$ select exists(select 1 from public.profiles where id = (select auth.uid()) and role = 'admin') $$;
revoke all on function private.is_admin() from public;
grant usage on schema private to authenticated;
grant execute on function private.is_admin() to authenticated;

create or replace function private.handle_new_user()
returns trigger language plpgsql security definer set search_path = ''
as $$ begin
  insert into public.profiles(id,email,full_name,role)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''),
    case when lower(new.email)='issamelkherrazi@gmail.com' then 'admin' else 'employee' end);
  return new;
end $$;
revoke all on function private.handle_new_user() from public;

create trigger on_auth_user_created after insert on auth.users
for each row execute procedure private.handle_new_user();

create table public.clients (
  id bigint generated by default as identity primary key, nom text, telephone text, email text, ville text,
  marchandises text, bon_payeur text, statut text, notes text,
  created_by uuid not null references auth.users(id), updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.commandes (
  id bigint generated by default as identity primary key, client text, produit text, type_container text, fournisseur text,
  date_commande date, statut text, booking text, ocean_freight_usd numeric, exchange_rate numeric,
  ocean_freight_rmb numeric, montant_container_rmb numeric, local_frais_rmb numeric, commission_pct numeric,
  commission_rmb numeric, autre_charge_rmb numeric, note_charge text, total_rmb numeric, total_usd numeric,
  paiements_json text, recu_payment_rmb numeric, reste_a_payer_rmb numeric, coc text,
  created_by uuid not null references auth.users(id), updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.factures (
  id bigint generated by default as identity primary key, commande_id bigint, client text, type text, montant numeric,
  devise text, date_facture date, envoyee text, comptable text,
  created_by uuid not null references auth.users(id), updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.paiements (
  id bigint generated by default as identity primary key, commande_id bigint, client text, montant_du numeric, recu numeric,
  devise text, echeance date, statut text,
  created_by uuid not null references auth.users(id), updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.livraisons (
  id bigint generated by default as identity primary key, commande_id bigint, reference text, depart text, destination text,
  eta date, container text, statut text, coc text,
  created_by uuid not null references auth.users(id), updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.factures_clients (
  id bigint generated by default as identity primary key, numero text, commande_id bigint, client text, date_facture date,
  lignes_json text, total_rmb numeric, total_usd numeric, recu_rmb numeric, reste_rmb numeric, notes text,
  created_by uuid not null references auth.users(id), updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create or replace function private.protect_audit_fields()
returns trigger language plpgsql set search_path = '' as $$ begin
  if new.created_by <> old.created_by then raise exception 'created_by is immutable'; end if;
  new.updated_at = now(); new.updated_by = (select auth.uid()); return new;
end $$;

do $$ declare t text; begin
  foreach t in array array['clients','commandes','factures','paiements','livraisons','factures_clients'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('create policy %I on public.%I for select to authenticated using (true)',t||'_select',t);
    execute format('create policy %I on public.%I for insert to authenticated with check (created_by=(select auth.uid()))',t||'_insert',t);
    execute format('create policy %I on public.%I for update to authenticated using (true) with check (true)',t||'_update',t);
    execute format('create policy %I on public.%I for delete to authenticated using ((select private.is_admin()))',t||'_delete_admin',t);
    execute format('create trigger protect_audit before update on public.%I for each row execute function private.protect_audit_fields()',t);
    execute format('grant select,insert,update,delete on public.%I to authenticated',t);
  end loop;
end $$;

alter table public.profiles enable row level security;
create policy profiles_select on public.profiles for select to authenticated using (true);
create policy profiles_update_admin on public.profiles for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
grant select,update on public.profiles to authenticated;
