create table if not exists public.frais_maroc_clients (
  id bigint generated by default as identity primary key, numero text, commande_id bigint, client text,
  date_frais date, transitaire_dhs numeric default 0, douane_dhs numeric default 0,
  coc_dhs numeric default 0, telex_dhs numeric default 0, portnet_dhs numeric default 0,
  frais_service_isa_dhs numeric default 0, autres_frais_json text default '[]', autre_total_dhs numeric default 0,
  tva_options_json text default '{}', sous_total_ht_dhs numeric default 0, tva_total_dhs numeric default 0,
  total_dhs numeric default 0, notes text, created_by uuid references auth.users(id) not null,
  updated_by uuid references auth.users(id), created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table public.frais_maroc_clients enable row level security;
grant select,insert,update,delete on public.frais_maroc_clients to authenticated;
grant usage,select on sequence public.frais_maroc_clients_id_seq to authenticated;
create policy frais_maroc_clients_select on public.frais_maroc_clients for select to authenticated using (true);
create policy frais_maroc_clients_insert on public.frais_maroc_clients for insert to authenticated with check (created_by=(select auth.uid()));
create policy frais_maroc_clients_update on public.frais_maroc_clients for update to authenticated using (true) with check (true);
create policy frais_maroc_clients_delete_admin on public.frais_maroc_clients for delete to authenticated using ((select private.is_admin()));
